### ISSUE TITLE
missing HibernateSearch in bom

### ISSUE THREAD

**Issue by tomlux** [wildfly/boms#10]
Hy,
it seems to me that the HibernateSearch libraries are missed in the BOM's?

Thanks
 Tom

**Comment by ctomc** [comment]
It is there see https://github.com/wildfly/boms/blob/master/jboss-javaee-7.0-with-hibernate/pom.xml#L124
how are you using it?

**Comment by tomlux** [comment]
Hmm, seems wrong usage on my part.
Here my error message:
 [ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-search-engine:jar is missing. @ line 24, column 21


See here my pom.xml: 
  https://gist.github.com/tomlux/8d4b6a9c2e119767c34a

Thanks, Tom

**Comment by ctomc** [comment]
Did you build beta3-snapshot? as currently it is exactly the same as released beta2 of pom. 
I will be able to take bit closer look later today.

**Comment by tomlux** [comment]
Just got it now working:
 https://gist.github.com/tomlux/47f969d1d603705af488

I had to add include the **type 'pom'** in the dependency
```xml
            <dependency>
                <groupId>org.wildfly.bom</groupId>
                <artifactId>jboss-javaee-7.0-with-all</artifactId>
                <version>9.0.0.Beta2</version>
				<type>pom</type>
                <scope>import</scope>
            </dependency>
```
