### ISSUE TITLE
org.wildfly.bom tag for 10.0.0.CR5

### ISSUE THREAD

**Issue by frekele** [wildfly/boms#17]
Hi

I am waiting for the artifact release 10.0.0.CR5 of org.wildfly.bom "wildfly-javaee7"  and "wildfly-javaee7-with-tools", but it seems that there is no comitt here a long time.

org.wildfly.bom is deprecated for 10.0.0.CR5 or after?

What should I use?

**Comment by ctomc** [comment]
Why would you think that it is deprecated and also no commit in long time? Last commit & release was when there was WildFly 10 CR4 released.

**Comment by ctomc** [comment]
10.0.0.CR5 boms released.

**Comment by frekele** [comment]
I was in doubt, I thought it might have changed the name of artifact.

Thank you @ctomc .
