### ISSUE TITLE
10.0.0.0.Final not available on maven central

### ISSUE THREAD

**Issue by JBodkin** [wildfly/boms#18]
Hello,

I'd like to use the bom for my project however the latest release isn't available on maven central. Please could you push the release up?

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.wildfly.bom%22%20AND%20a%3A%22wildfly-javaee7%22

**Comment by ctomc** [comment]
Release was published in repository.jboss.org few hours ago, but it takes up to a day to be synced to maven central.
So you would need wait a bit to be synced or use jboss.org maven repo in mean time.
You could also use CR5 version of boms in mean time as they are pretty much identical to .Final ones.
