### ISSUE TITLE
Maven Central Repository

### ISSUE THREAD

**Issue by alexandreogrodovski** [wildfly/boms#25]
I'm trying to use the latest version of Wildfly bill-of-materials, but it is not in Maven Central Repository. Could somebody deploy this version there?

Thanks.

**Comment by ctomc** [comment]
@jamezp could you setup this?

**Comment by jamezp** [comment]
They seem to already be syncing http://search.maven.org/#search%7Cga%7C1%7Corg.wildfly.bom
