### ISSUE TITLE
Apache CXF exclusion is invalid in WildFly 10.1.0.Final BOM

### ISSUE THREAD

**Issue by krisztiankocsis** [wildfly/boms#31]
The org.apache.cxf -> cxf-core has an exclusion with groupId = \* and artifactId = *. This causes errors in some POM parsers (like nebula-dependency-recommender-plugin Gradle plugin). What does it actually mean?

**Comment by ctomc** [comment]
This are wildcard exclusions. It is a feature that was added to maven in 3.2.1
see more details in release notes https://maven.apache.org/docs/3.2.1/release-notes.html
I would recommend looking if maybe newer version of nebula plugin has already fixed that or that you suggest nebula guys to fix it. Their repo is at https://github.com/nebula-plugins/nebula-dependency-recommender-plugin
