### ISSUE TITLE
Invalid entries in dependencyManagement

### ISSUE THREAD

**Issue by reitzmichnicht** [wildfly/boms#38]
Hi

There are 5 entries that are invalid in the Wildfly Bom. This affects version 13.0.0.Final and current master

4 Entries use the property $version.org.jboss.security.negotiation which is not defined.
And org.jboss.resteasy:async-http-servlet-3.0 points to a version which is not available.

Kind regards,
Michael

**Comment by emmartins** [comment]
fixed/outdated
